import { Vehicle, Order, Part, Customer, Appointment, Technician, TeamActivity, StockMovement } from "./types";

export const MOCK_TECHNICIANS: Technician[] = [
  {
    id: "t1",
    name: "Moussa Traoré",
    specialty: "Mécanique Générale",
    status: "BUSY",
    efficiency: 94,
    completedJobs: 142,
    currentOrderId: "OT-2026-00142",
  },
  {
    id: "t2",
    name: "Kevin Kamga",
    specialty: "Électricité Auto",
    status: "AVAILABLE",
    efficiency: 88,
    completedJobs: 128,
  },
  {
    id: "t3",
    name: "Alain Foka",
    specialty: "Diagnostic & Électronique",
    status: "AWAY",
    efficiency: 82,
    completedJobs: 95,
  },
  {
    id: "t4",
    name: "Sébastien Eto'o",
    specialty: "Carrosserie",
    status: "AVAILABLE",
    efficiency: 91,
    completedJobs: 110,
  },
];

export const MOCK_TEAM_ACTIVITY: TeamActivity[] = [
  {
    id: "act-1",
    technicianId: "t1",
    technicianName: "Moussa Traoré",
    action: "A commencé le démontage",
    orderId: "OT-2026-00142",
    timestamp: "2026-04-14T10:30:00Z",
  },
  {
    id: "act-2",
    technicianId: "t2",
    technicianName: "Kevin Kamga",
    action: "A terminé le diagnostic",
    orderId: "OT-2026-00140",
    timestamp: "2026-04-14T09:45:00Z",
  },
  {
    id: "act-3",
    technicianId: "t1",
    technicianName: "Moussa Traoré",
    action: "A ajouté des pièces au stock",
    timestamp: "2026-04-14T08:15:00Z",
  },
  {
    id: "act-4",
    technicianId: "t3",
    technicianName: "Alain Foka",
    action: "Est parti en pause déjeuner",
    timestamp: "2026-04-14T12:00:00Z",
  },
];

export const MOCK_CUSTOMERS: Customer[] = [
  {
    id: "c1",
    name: "Saliou Diallo",
    email: "saliou.diallo@email.cm",
    phone: "+237 699 00 11 22",
    address: "Bastos, Yaoundé",
    createdAt: "2025-01-15",
  },
  {
    id: "c2",
    name: "Marie Ngo",
    email: "m.ngo@email.cm",
    phone: "+237 677 33 44 55",
    address: "Akwa, Douala",
    createdAt: "2025-02-20",
  },
  {
    id: "c3",
    name: "Paul Biya",
    email: "p.biya@email.cm",
    phone: "+237 655 66 77 88",
    address: "Etoudi, Yaoundé",
    createdAt: "2024-11-10",
  },
];

export const MOCK_VEHICLES: Vehicle[] = [
  {
    id: "v1",
    plate: "LT-4521-A",
    brand: "Toyota",
    model: "Hilux",
    year: 2022,
    vin: "TYT1234567890HIL",
    mileage: 45000,
    customerId: "c1",
    customerName: "Saliou Diallo",
    lastVisit: "2026-03-10",
  },
  {
    id: "v2",
    plate: "CE-8892-B",
    brand: "Mercedes",
    model: "C200",
    year: 2019,
    vin: "WDB2040011A123456",
    mileage: 82000,
    customerId: "c2",
    customerName: "Marie Ngo",
    lastVisit: "2026-04-01",
  },
  {
    id: "v3",
    plate: "LT-1102-C",
    brand: "Suzuki",
    model: "Vitara",
    year: 2021,
    vin: "SUZ9876543210VIT",
    mileage: 28000,
    customerId: "c3",
    customerName: "Paul Biya",
    lastVisit: "2026-04-12",
  },
];

export const MOCK_ORDERS: Order[] = [
  {
    id: "OT-2026-00142",
    vehicleId: "v1",
    vehicleName: "Toyota Hilux",
    plate: "LT-4521-A",
    customerId: "c1",
    customerName: "Saliou Diallo",
    status: "IN_PROGRESS",
    priority: "HIGH",
    description: "Révision complète + changement plaquettes",
    diagnostic: "Plaquettes de frein avant usées à 90%. Filtres encrassés.",
    createdAt: "2026-04-14T08:00:00Z",
    updatedAt: "2026-04-14T10:00:00Z",
    estimatedTime: "4h",
    technicianId: "t1",
    technicianName: "Moussa Traoré",
    parts: [
      { id: "pe1", partId: "p1", name: "Filtre à huile Toyota", quantity: 1, unitPrice: 8500 },
      { id: "pe2", partId: "p2", name: "Plaquettes de frein", quantity: 1, unitPrice: 45000 },
    ],
    labor: [
      { id: "le1", description: "Main d'œuvre révision", hours: 2, rate: 15000 },
      { id: "le2", description: "Remplacement plaquettes", hours: 1, rate: 15000 },
    ],
    totalAmount: 98500,
  },
  {
    id: "OT-2026-00143",
    vehicleId: "v2",
    vehicleName: "Mercedes C200",
    plate: "CE-8892-B",
    customerId: "c2",
    customerName: "Marie Ngo",
    status: "RECEIVED",
    priority: "MEDIUM",
    description: "Bruit suspect train avant",
    createdAt: "2026-04-14T09:30:00Z",
    updatedAt: "2026-04-14T09:30:00Z",
    estimatedTime: "2h",
    parts: [],
    labor: [],
  },
];

export const MOCK_APPOINTMENTS: Appointment[] = [
  {
    id: "a1",
    customerId: "c1",
    customerName: "Saliou Diallo",
    vehicleName: "Toyota Hilux",
    date: "2026-04-15",
    time: "08:30",
    type: "Révision",
    status: "CONFIRMED",
  },
  {
    id: "a2",
    customerId: "c4",
    customerName: "Jean Kengne",
    vehicleName: "BMW X5",
    date: "2026-04-15",
    time: "10:00",
    type: "Diagnostic moteur",
    status: "PENDING",
  },
  {
    id: "a3",
    customerId: "c5",
    customerName: "Alice Zanga",
    vehicleName: "Hyundai Santa Fe",
    date: "2026-04-15",
    time: "14:30",
    type: "Climatisation",
    status: "CONFIRMED",
  },
];

export const MOCK_PARTS: Part[] = [
  {
    id: "p1",
    code: "FIL-OIL-TY",
    name: "Filtre à huile Toyota",
    category: "Filtration",
    quantity: 15,
    minThreshold: 5,
    price: 8500,
  },
  {
    id: "p2",
    code: "BRK-PAD-MB",
    name: "Plaquettes de frein Mercedes",
    category: "Freinage",
    quantity: 3,
    minThreshold: 4,
    price: 45000,
  },
];

export const MOCK_STOCK_MOVEMENTS: StockMovement[] = [
  {
    id: "m1",
    partId: "p1",
    partName: "Filtre à huile Toyota",
    type: "IN",
    quantity: 20,
    reason: "Achat fournisseur",
    timestamp: "2026-04-10T09:00:00Z",
  },
  {
    id: "m2",
    partId: "p1",
    partName: "Filtre à huile Toyota",
    type: "OUT",
    quantity: 1,
    reason: "Utilisation OT-2026-00142",
    orderId: "OT-2026-00142",
    technicianId: "t1",
    technicianName: "Moussa Traoré",
    timestamp: "2026-04-14T10:30:00Z",
  },
  {
    id: "m3",
    partId: "p2",
    partName: "Plaquettes de frein Mercedes",
    type: "OUT",
    quantity: 1,
    reason: "Utilisation OT-2026-00142",
    orderId: "OT-2026-00142",
    technicianId: "t1",
    technicianName: "Moussa Traoré",
    timestamp: "2026-04-14T10:35:00Z",
  },
  {
    id: "m4",
    partId: "p2",
    partName: "Plaquettes de frein Mercedes",
    type: "ADJUSTMENT",
    quantity: -1,
    reason: "Inventaire - Casse",
    timestamp: "2026-04-12T15:00:00Z",
  },
];

export const MOCK_INVOICES = [
  {
    id: "FAC-2026-00089",
    customer: "Saliou Diallo",
    vehicle: "Toyota Hilux (LT-4521-A)",
    amount: 145000,
    status: "PAID",
    date: "2026-04-10",
  },
  {
    id: "FAC-2026-00090",
    customer: "Marie Ngo",
    vehicle: "Mercedes C200 (CE-8892-B)",
    amount: 85000,
    status: "PENDING",
    date: "2026-04-12",
  },
  {
    id: "FAC-2026-00091",
    customer: "Paul Biya",
    vehicle: "Suzuki Vitara (LT-1102-C)",
    amount: 250000,
    status: "OVERDUE",
    date: "2026-04-05",
  },
];

export const MOCK_QUOTES = [
  {
    id: "DEV-2026-00042",
    customer: "Jean Kengne",
    vehicle: "BMW X5 (CE-1234-X)",
    amount: 350000,
    status: "SENT",
    date: "2026-04-14",
  },
  {
    id: "DEV-2026-00043",
    customer: "Alice Zanga",
    vehicle: "Hyundai Santa Fe (LT-9876-Z)",
    amount: 125000,
    status: "ACCEPTED",
    date: "2026-04-13",
  },
];
